### ISSUE TITLE
"no such table: posts" during installation

### ISSUE THREAD

**Issue by akmalelias** [dotsistemas/wpanel#26]
Hi,

I'm following instruction in this wiki
https://github.com/dotsistemas/wpanel/wiki/Installation

But after acquire the code, access the public folder and run PHP embedded server, I encountered this error:
Message: SQLite3::query(): Unable to prepare statement: 1, no such table: posts

I try using mysql also hitting same error & I can't find any sql file that can be imported to create the table. Please advise. Thanks

**Comment by elieldepaula** [comment]
Hi, Akmal, I'm sorry about that, I'm preparing a new doc for the project. But You can follow the steps below to finish the setup:

1. After run PHP embeded server;
2. Access the URL http://localhost:8000/index.php/setup

This step will create the database according to the setup on /public/config/database.php

Let me know if you have success or no ok?

Thanks.

**Comment by akmalelias** [comment]
Ok thanks, it is working now. May I know, when do u plan to release next version with all the latest changes after version 4.0.0?

**Comment by elieldepaula** [comment]
Hi Akmal, I'm trying to keep some regular rhythm of updates on each 6 months with minor bug fixes in the interval. It's my chalenge because I have to divide time with my work.

I pretend to release a new version on this weekend, mostly because of the new version of CodeIgniter and some other improvements.

You can also taste the 'develop' branch with relative secury because the project is pretty stable.

**Comment by akmalelias** [comment]
ok noted with thanks
